In [2]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df = pd.read_csv("autos_dataset.csv")

In [4]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.4,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.4,8.0,115,5500,18,22,17450

In [5]:
df.shape

(205, 26)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

In [7]:
df.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [8]:
df.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [9]:
df.head(2).T

                             0            1
symboling                    3            3
normalized-losses            ?            ?
make               alfa-romero  alfa-romero
fuel-type                  gas          gas
aspiration                 std          std
num-of-doors               two          two
body-style         convertible  convertible
drive-wheels               rwd          rwd
engine-location          front        front
wheel-base                88.6         88.6
length                   168.8        168.8
width                     64.1         64.1
height                    48.8         48.8
curb-weight               2548         2548
engine-type               dohc         dohc
num-of-cylinders          four         four
engine-size                130          130
fuel-system               mpfi         mpfi
bore                      3.47         3.47
stroke                    2.68         2.68
compression-ratio            9            9
horsepower                 111          111
peak-rpm                  5000         5000
city-mpg                    21           21
highway-mpg                 27           27
price                    13495        16500

In [10]:
df.dtypes

symboling              int64
normalized-losses     object
make                  object
fuel-type             object
aspiration            object
num-of-doors          object
body-style            object
drive-wheels          object
engine-location       object
wheel-base           float64
length               float64
width                float64
height               float64
curb-weight            int64
engine-type           object
num-of-cylinders      object
engine-size            int64
fuel-system           object
bore                  object
stroke                object
compression-ratio    float64
horsepower            object
peak-rpm              object
city-mpg               int64
highway-mpg            int64
price                 object
dtype: object

In [11]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,195,196,197,198,199,200,201,202,203,204
symboling,3,3,1,2,2,2,1,1,1,0,...,-1,-2,-1,-2,-1,-1,-1,-1,-1,-1
normalized-losses,?,?,?,164,164,?,158,?,158,?,...,74,103,74,103,74,95,95,95,95,95
make,alfa-romero,alfa-romero,alfa-romero,audi,audi,audi,audi,audi,audi,audi,...,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo,volvo
fuel-type,gas,gas,gas,gas,gas,gas,gas,gas,gas,gas,...,gas,gas,gas,gas,gas,gas,gas,gas,diesel,gas
aspiration,std,std,std,std,std,std,std,std,turbo,turbo,...,std,std,std,turbo,turbo,std,turbo,std,turbo,turbo
num-of-doors,two,two,two,four,four,two,four,four,four,two,...,four,four,four,four,four,four,four,four,four,four
body-style,convertible,convertible,hatchback,sedan,sedan,sedan,sedan,wagon,sedan,hatchback,...,wagon,sedan,wagon,sedan,wagon,sedan,sedan,sedan,sedan,sedan
drive-wheels,rwd,rwd,rwd,fwd,4wd,fwd,fwd,fwd,fwd,4wd,...,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd,rwd
engine-location,front,front,front,front,front,front,front,front,front,front,...,front,front,front,front,front,front,front,front,front,front
wheel-base,88.6,88.6,94.5,99.8,99.4,99.8,105.8,105.8,105.8,99.5,...,104.3,104.3,104.3,104.3,104.3,109.1,109.1,109.1,109.1,109.1
length,168.8,168.8,171.2,176.6,176.6,177.3,192.7,192.7,192.7,178.2,...,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8,188.8
width,64.1,64.1,65.5,66.2,66.4,66.3,71.4,71.4,71.4,67.9,...,67.2,67.2,67.2,67.2,67.2,68.9,68.8,68.9,68.9,68.9
height,48.8,48.8,52.4,54.3,54.3,53.1,55.7,55.7,55.9,52,...,57.5,56.2,57.5,56.2,57.5,55.5,55.5,55.5,55.5,55.5
curb-weight,2548,2548,2823,2337,2824,2507,2844,2954,3086,3053,...,3034,2935,3042,3045,3157,2952,3049,3012,3217,3062
engine-type,dohc,dohc,ohcv,ohc,ohc,ohc,ohc,ohc,ohc,ohc,...,ohc,ohc,ohc,ohc,ohc,ohc,ohc,ohcv,ohc,ohc
num-of-cylinders,four,four,six,four,five,five,five,five,five,five,...,four,four,four,four,four,four,four,six,six,four
engine-size,130,130,152,109,136,136,136,136,131,131,...,141,141,141,130,130,141,141,173,145,141
fuel-system,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,...,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,mpfi,idi,mpfi
bore,3.47,3.47,2.68,3.19,3.19,3.19,3.19,3.19,3.13,3.13,...,3.78,3.78,3.78,3.62,3.62,3.78,3.78,3.58,3.01,3.78
stroke,2.68,2.68,3.47,3.4,3.4,3.4,3.4,3.4,3.4,3.4,...,3.15,3.15,3.15,3.15,3.15,3.15,3.15,2.87,3.4,3.15
compression-ratio,9,9,9,10,8,8.5,8.5,8.5,8.3,7,...,9.5,9.5,9.5,7.5,7.5,9.5,8.7,8.8,23,9.5
horsepower,111,111,154,102,115,110,110,110,140,160,...,114,114,114,162,162,114,160,134,106,114
peak-rpm,5000,5000,5000,5500,5500,5500,5500,5500,5500,5500,...,5400,5400,5400,5100,5100,5400,5300,5500,4800,5400
city-mpg,21,21,19,24,18,19,19,19,17,16,...,23,24,24,17,17,23,19,18,26,19
highway-mpg,27,27,26,30,22,25,25,25,20,22,...,28,28,28,22,22,28,25,23,27,25
price,13495,16500,16500,13950,17450,15250,17710,18920,23875,?,...,13415,15985,16515,18420,18950,16845,19045,21485,22470,22625

In [13]:
# help(df.T)